
export interface PAOEntry {
  number: string;
  person: string;
  action: string;
  object: string;
  etymology: string;
  icon: string;
}

export const PAO_DATABASE: PAOEntry[] = [
  { number: "00", person: "Obelix", action: "Menggendong", object: "Menhir", etymology: "Bentuk bulat batu Menhir", icon: "User" },
  { number: "01", person: "Iron Man", action: "Meluncurkan", object: "Roket", etymology: "Posisi terbang vertikal (angka 1)", icon: "Rocket" },
  { number: "02", person: "Zorro", action: "Menggores", object: "Huruf Z", etymology: "Lekukan alur huruf Z (angka 2)", icon: "Sword" },
  { number: "03", person: "Batman", action: "Melempar", object: "Batarang", etymology: "Mirip sayap Batarang", icon: "Zap" },
  { number: "04", person: "Aladdin", action: "Menggosok", object: "Lampu Ajaib", etymology: "Garis membentuk huruf A", icon: "Flame" },
  { number: "05", person: "Superman", action: "Membusungkan", object: "Logo S", etymology: "Garis atas & lengkung mirip S", icon: "Shield" },
  { number: "06", person: "Gatotkaca", action: "Meninju", object: "Bumi", etymology: "Perut mirip huruf G", icon: "Globe" },
  { number: "07", person: "Joker", action: "Menembakkan", object: "Pistol", etymology: "Mirip huruf J atau Pistol", icon: "Crosshair" },
  { number: "08", person: "The Thing", action: "Menghancurkan", object: "Tembok Batu", etymology: "Bentuk gempal bertumpuk", icon: "Hammer" },
  { number: "09", person: "Thor", action: "Mengayunkan", object: "Mjolnir", etymology: "Kepala bulat palu (angka 9)", icon: "Hammer" },
  { number: "10", person: "Maradona", action: "Menepuk", object: "Bola", etymology: "Nomor punggung legendaris", icon: "Trophy" },
  { number: "11", person: "Algojo", action: "Menendang", object: "Titik Putih", etymology: "11 Meter jarak penalti", icon: "Footprints" },
  { number: "12", person: "Suporter", action: "Mengibarkan", object: "Bendera", etymology: "Pemain ke-12", icon: "Flag" },
  { number: "13", person: "Kiper Sial", action: "Kebobolan", object: "Jaring Gawang", etymology: "Unlucky 13", icon: "Skull" },
  { number: "14", person: "Cupid", action: "Memanah", object: "Busur Hati", etymology: "14 Februari", icon: "Heart" },
  { number: "15", person: "Pemain Lelah", action: "Terkapar", object: "Botol Oksigen", etymology: "15 Menit perpanjangan waktu", icon: "GlassWater" },
  { number: "16", person: "Master Catur", action: "Membanting", object: "Papan Catur", etymology: "16 Bidak catur satu warna", icon: "Grid3x3" },
  { number: "17", person: "Pejuang 45", action: "Memanjat", object: "Pohon Pinang", etymology: "17 Agustus", icon: "Mountain" },
  { number: "18", person: "Polisi", action: "Menilang", object: "Surat Tilang", etymology: "18 Tahun usia minimal SIM", icon: "Car" },
  { number: "19", person: "Dokter APD", action: "Menyemprotkan", object: "Disinfektan", etymology: "COVID-19", icon: "Syringe" },
  { number: "20", person: "Penari Jawa", action: "Menari", object: "Gamelan", etymology: "20 digit jari tangan & kaki", icon: "Music" },
  { number: "21", person: "R.A. Kartini", action: "Menulis", object: "Buku Diary", etymology: "21 April", icon: "BookOpen" },
  { number: "22", person: "Gajah Mada", action: "Mengucap", object: "Buah Palapa", etymology: "Mirip dua angsa (Sumpah Setia)", icon: "Shield" },
  { number: "23", person: "Julius Caesar", action: "Menikam", object: "Jubah Toga", etymology: "23 tusukan kematian Caesar", icon: "Sword" },
  { number: "24", person: "Pembalap F1", action: "Mengganti", object: "Stopwatch", etymology: "24 Jam (Le Mans)", icon: "Timer" },
  { number: "25", person: "Sinterklas", action: "Memanggul", object: "Karung Hadiah", etymology: "25 Desember", icon: "Gift" },
  { number: "26", person: "Tsunami", action: "Menerjang", object: "Gelombang", etymology: "26 Desember (Aceh)", icon: "Waves" },
  { number: "27", person: "Gitaris Rock", action: "Memetik", object: "Gitar Listrik", etymology: "27 Club (usia kematian legenda)", icon: "Music" },
  { number: "28", person: "Pemuda 28", action: "Mengikrarkan", object: "Naskah Sumpah", etymology: "28 Oktober (Sumpah Pemuda)", icon: "Scroll" },
  { number: "29", person: "Orang Kaya", action: "Mengemis", object: "Kaleng Kosong", etymology: "1929 (Depresi Ekonomi)", icon: "Coins" },
  { number: "30", person: "Yudas", action: "Menghitung", object: "Keping Perak", etymology: "30 Keping Perak pengkhianatan", icon: "CircleDollarSign" },
  { number: "31", person: "Pasukan 313", action: "Menhujam", object: "Tameng Besi", etymology: "Jumlah pasukan perang Badr", icon: "Shield" },
  { number: "32", person: "Dokter Gigi", action: "Mencabut", object: "Gigi Geraham", etymology: "32 Gigi permanen manusia", icon: "Stethoscope" },
  { number: "33", person: "Petasbih", action: "Memutar", object: "Biji Tasbih", etymology: "33 kali wirid/zikir", icon: "Orbit" },
  { number: "34", person: "Sopir Truk", action: "Membunyikan", object: "Klakson", etymology: "Jalur Pantura legendaris", icon: "Truck" },
  { number: "35", person: "Fotografer", action: "Menggulung", object: "Roll Film", etymology: "35mm ukuran standar film", icon: "Camera" },
  { number: "36", person: "Pemain Congklak", action: "Menjatuhkan", object: "Papan Congklak", etymology: "Bentuk biji congklak", icon: "Dices" },
  { number: "37", person: "Pasien Demam", action: "Menggigil", object: "Termometer", etymology: "37 derajat Celcius (normal)", icon: "Thermometer" },
  { number: "38", person: "Koboi", action: "Menarik", object: "Pelatuk Revolver", etymology: ".38 Special kaliber peluru", icon: "Crosshair" },
  { number: "39", person: "Ibu Panik", action: "Melihat", object: "Suhu Tinggi", etymology: "Ambang batas demam tinggi", icon: "AlertTriangle" },
  { number: "40", person: "Ali Baba", action: "Membuka", object: "Peti Harta", etymology: "40 Penyamun", icon: "Key" },
  { number: "41", person: "Prajurit", action: "Long March", object: "Ransel Kanvas", etymology: "Nomor batalyon/satuan", icon: "Backpack" },
  { number: "42", person: "Tentara Jepang", action: "Mendarat", object: "Sepeda Onthel", etymology: "1942 masuk Indonesia", icon: "Bike" },
  { number: "43", person: "Relawan", action: "Menyelamatkan", object: "Abu Vulkanik", etymology: "Detak jantung panik", icon: "Flame" },
  { number: "44", person: "Obama", action: "Berpidato", object: "Podium", etymology: "Presiden ke-44 AS", icon: "Mic" },
  { number: "45", person: "Soekarno", action: "Membaca", object: "Teks Proklamasi", etymology: "1945 tahun Kemerdekaan", icon: "PenTool" },
  { number: "46", person: "Rossi", action: "Menikung", object: "Motor Balap", etymology: "Nomor ikonik VR46", icon: "Bike" },
  { number: "47", person: "Agent 47", action: "Mengintai", object: "Peredam Suara", etymology: "Kode nama Hitman", icon: "Target" },
  { number: "48", person: "Diplomat PBB", action: "Menandatangani", object: "Naskah HAM", etymology: "1948 Deklarasi HAM", icon: "Globe" },
  { number: "49", person: "Penambang", action: "Mengayak", object: "Nampan Emas", etymology: "49ers (1849)", icon: "Gem" },
  { number: "50", person: "Penerima Zakat", action: "Mengantre", object: "Gandum", etymology: "50:50 berbagi rata", icon: "Scale" },
  { number: "51", person: "Pemanah Uhud", action: "Melepaskan", object: "Anak Panah", etymology: "Mirip busur panah ditarik", icon: "Compass" },
  { number: "52", person: "Thariq b. Ziyad", action: "Membakar", object: "Kapal Perang", etymology: "52 minggu (tak pulang)", icon: "Ship" },
  { number: "53", person: "Nabi Muhammad", action: "Berhijrah", object: "Unta Putih", etymology: "53 Tahun usia saat Hijrah", icon: "Map" },
  { number: "54", person: "Sultan Boabdil", action: "Menyerahkan", object: "Kunci Emas", etymology: "Mirip kunci kuno besar", icon: "Key" },
  { number: "55", person: "Abdurrahman I", action: "Menanam", object: "Pohon Kurma", etymology: "Dua batang pohon sejajar", icon: "TreePalm" },
  { number: "56", person: "Utsman b. Affan", action: "Mengumpulkan", object: "Mushaf", etymology: "Mirip orang sedang sujud", icon: "BookOpen" },
  { number: "57", person: "Pasukan Gajah", action: "Menginjak", object: "Batu Sijjil", etymology: "570 M tahun Gajah", icon: "Footprints" },
  { number: "58", person: "Cendekiawan", action: "Menenggelamkan", object: "Tinta/Buku", etymology: "Mirip kacamata", icon: "Glasses" },
  { number: "59", person: "Al-Fatih", action: "Menarik", object: "Rantai Besi", etymology: "Penaklukan Konstantinopel", icon: "Link" },
  { number: "60", person: "Warga Sipil", action: "Bersembunyi", object: "Bunker", etymology: "60 Menit (detik akhir)", icon: "ShieldAlert" },
  { number: "61", person: "Yuri Gagarin", action: "Melayang", object: "Vostok", etymology: "1961 ke luar angkasa", icon: "Telescope" },
  { number: "62", person: "Pasukan Damai", action: "Menjaga", object: "Garis Batas", etymology: "+62 Kode telepon Indonesia", icon: "Phone" },
  { number: "63", person: "J.F. Kennedy", action: "Terkulai", object: "Mobil Terbuka", etymology: "1963 pembunuhan JFK", icon: "Car" },
  { number: "64", person: "Mandela Muda", action: "Menggenggam", object: "Jeruji", etymology: "1964 vonis seumur hidup", icon: "Lock" },
  { number: "65", person: "Pahlawan Rev.", action: "Diculik", object: "Truk Militer", etymology: "1965 Tragedi G30S", icon: "Truck" },
  { number: "66", person: "Mahasiswa 66", action: "Berdemo", object: "Jaket Kuning", etymology: "Angkatan 66", icon: "Megaphone" },
  { number: "67", person: "Tentara Arab", action: "Menangisi", object: "Yerusalem", etymology: "1967 Perang 6 Hari", icon: "Flag" },
  { number: "68", person: "Martin L. King", action: "Membasuh", object: "Mimbar", etymology: "1968 pembunuhan MLK", icon: "Mic" },
  { number: "69", person: "Armstrong", action: "Memancangkan", object: "Bendera", etymology: "1969 pendaratan di Bulan", icon: "Moon" },
  { number: "70", person: "Anwar Sadat", action: "Menyeberangi", object: "Terusan Suez", etymology: "Era perang Yom Kippur", icon: "Ship" },
  { number: "71", person: "Pengungsi", action: "Memikul", object: "Kuali Tembaga", etymology: "1971 perang Bangladesh", icon: "Briefcase" },
  { number: "72", person: "Atlet Munchen", action: "Terikat", object: "Penutup Mata", etymology: "1972 tragedi Olimpiade", icon: "EyeOff" },
  { number: "73", person: "Antrian Minyak", action: "Menyeret", object: "Jerigen Kosong", etymology: "1973 krisis minyak", icon: "Package" },
  { number: "74", person: "Richard Nixon", action: "Melambai", object: "Pintu Heli", etymology: "1974 Nixon mundur", icon: "Hand" },
  { number: "75", person: "Warga Timor", action: "Mengungsi", object: "Kapal Kayu", etymology: "1975 integrasi Timor", icon: "Sailboat" },
  { number: "76", person: "Steve Wozniak", action: "Merakit", object: "Papan Sirkuit", etymology: "1976 berdirinya Apple", icon: "Cpu" },
  { number: "77", person: "Korban Pesawat", action: "Terbakar", object: "Sayap Pesawat", etymology: "1977 tragedi Tenerife", icon: "Plane" },
  { number: "78", person: "Imam Khomeini", action: "Pulang", object: "Tangga Pesawat", etymology: "1978 Revolusi Iran", icon: "Plane" },
  { number: "79", person: "Juhayman", action: "Mengepung", object: "Ka'bah", etymology: "1979 pengepungan Haram", icon: "Castle" },
  { number: "80", person: "John Lennon", action: "Terjatuh", object: "Kacamata Bulat", etymology: "1980 pembunuhan Lennon", icon: "Glasses" },
  { number: "81", person: "Anwar Sadat", action: "Tertembak", object: "Podium Parade", etymology: "1981 pembunuhan Sadat", icon: "Target" },
  { number: "82", person: "Bunda Teresa", action: "Memeluk", object: "Anak Yatim", etymology: "1982 gencatan Beirut", icon: "HeartHandshake" },
  { number: "83", person: "S. Petrov", action: "Menolak", object: "Tombol Nuklir", etymology: "1983 pria penyelamat dunia", icon: "Bomb" },
  { number: "84", person: "Korban Bhopal", action: "Menutup Mata", object: "Tabung Gas", etymology: "1984 bencana kimia Bhopal", icon: "Biohazard" },
  { number: "85", person: "Putri Diana", action: "Menyalami", object: "Tangan Pasien", etymology: "1985 Diana & pasien AIDS", icon: "Handshake" },
  { number: "86", person: "Petugas Nuklir", action: "Memadamkan", object: "Chernobyl", etymology: "1986 tragedi Chernobyl", icon: "Radiation" },
  { number: "87", person: "Mandela Tua", action: "Menunggu", object: "Piring Kaleng", etymology: "Akhir masa penjara", icon: "Timer" },
  { number: "88", person: "Saddam H.", action: "Menghirup", object: "Gas Beracun", etymology: "1988 tragedi Halabja", icon: "Wind" },
  { number: "89", person: "Warga Berlin", action: "Menghancurkan", object: "Tembok Berlin", etymology: "1989 runtuhnya Tembok", icon: "Construction" },
  { number: "90", person: "Nelson Mandela", action: "Mengepalkan", object: "Tangan", etymology: "1990 kebebasan Mandela", icon: "Hand" },
  { number: "91", person: "Freddie Mercury", action: "Bernyanyi", object: "Microphone", etymology: "1991 wafat sang legenda", icon: "Mic2" },
  { number: "92", person: "Pasukan PBB", action: "Membagikan", object: "Roti", etymology: "1992 kelaparan Somalia", icon: "Wheat" },
  { number: "93", person: "Yasser Arafat", action: "Berjabat Tangan", object: "Tangan Musuh", etymology: "1993 Damai Oslo", icon: "Handshake" },
  { number: "94", person: "Korban Rwanda", action: "Bersembunyi", object: "Parang", etymology: "1994 Genosida Rwanda", icon: "Sword" },
  { number: "95", person: "Ibu Srebrenica", action: "Meraba", object: "Nisan Putih", etymology: "1995 Genosida Bosnia", icon: "Landmark" },
  { number: "96", person: "Muhammad Ali", action: "Menyulut", object: "Obor", etymology: "1996 Api Olimpiade", icon: "Flame" },
  { number: "97", person: "Putri Diana", action: "Menghindari", object: "Kamera", etymology: "1997 wafatnya Diana", icon: "Camera" },
  { number: "98", person: "Aktivis 98", action: "Menduduki", object: "Atap Gedung DPR", etymology: "1998 Reformasi Indonesia", icon: "Building" },
  { number: "99", person: "BJ Habibie", action: "Melepas", object: "Pesawat Kertas", etymology: "1999 Habibie lepas jabatan", icon: "Plane" }
];
